version: "3.9"

services:
  webapp:
    build: .  # Path where your Dockerfile is located
    container_name: webapp
    ports:
      - "8080:80"
    restart: always   # Ensures container restarts if it crashes
